name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  setup-sever:
    name: Server Initialization
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/aws-personal-key.pem
          chmod 600 ~/.ssh/aws-personal-key.pem

      - name: Terraform Init
        run: terraform init
        working-directory: ./server-init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./server-init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}